build : Update Dockerfile
 => [5/6] COPY . .                                                                                                                 1.4s
 => ERROR [6/6] RUN yarn build:soaf                                                                                                2.4s
------
 > [6/6] RUN yarn build:soaf:
2.366 Usage Error: The project in /app/package.json doesn't seem to have been installed - running an install there might help
2.366 
2.366 $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
------
Dockerfile:17
--------------------
  15 |     
  16 |     # Step 6: Build the project
  17 | >>> RUN yarn build:soaf
  18 |     
  19 |     # Step 7: Expose the application port (default is 4173 for Vite preview)
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn build:soaf" did not complete successfully: exit code: 1